services:
  kr_test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - ROS_DISTRO=foxy
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      NVIDIA_DRIVER_CAPABILITIES: all
      ROS_LOG_DIR: /tmp
      ROS_DOMAIN_ID: 10
    container_name: kr_test
    entrypoint: /entrypoint.bash
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    ulimits:
      nofile:
        soft: 2048
        hard: 40000
    user: ${CURRENT_UID}  # CURRENT_UID=$(id -u):$(id -g)
    volumes:
      - ~/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/hosts:/etc/hosts
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
